name = "arbitragex-edge"
main = "src/index.ts"
compatibility_date = "2024-09-08"
compatibility_flags = ["nodejs_compat"]

# ========================================
# D1 Database Edge (Distributed Backend Cache)
# ========================================
[[d1_databases]]
binding = "OPPORTUNITIES_CACHE"
database_name = "arbitragex-opportunities-cache"
database_id = "your-opportunities-database-id"

[[d1_databases]]
binding = "STRATEGIES_CACHE"
database_name = "arbitragex-strategies-cache"
database_id = "your-strategies-database-id"

[[d1_databases]]
binding = "METRICS_CACHE"
database_name = "arbitragex-metrics-cache"
database_id = "your-metrics-database-id"

[[d1_databases]]
binding = "SESSIONS_CACHE"
database_name = "arbitragex-sessions-cache"
database_id = "your-sessions-database-id"

# ========================================
# KV Storage Edge (Backend Cache)
# ========================================
[[kv_namespaces]]
binding = "API_CACHE"
id = "your-api-cache-namespace-id"
preview_id = "your-api-cache-preview-id"

[[kv_namespaces]]
binding = "SESSIONS"
id = "your-sessions-namespace-id"
preview_id = "your-sessions-preview-id"

[[kv_namespaces]]
binding = "PERFORMANCE_METRICS"
id = "your-performance-namespace-id"
preview_id = "your-performance-preview-id"

[[kv_namespaces]]
binding = "CONFIG_CACHE"
id = "your-config-namespace-id"
preview_id = "your-config-preview-id"

# ========================================
# R2 Storage (Backend Asset & Log Storage)
# ========================================
[[r2_buckets]]
binding = "BACKEND_ASSETS"
bucket_name = "arbitragex-backend-assets"

[[r2_buckets]]
binding = "EDGE_LOGS"
bucket_name = "arbitragex-edge-logs"

[[r2_buckets]]
binding = "CONFIG_BACKUPS"
bucket_name = "arbitragex-config-backups"

# ========================================
# Pub/Sub (Backend Real-time Messaging)
# ========================================
[[pubsub]]
binding = "BACKEND_EVENTS"
namespace = "arbitragex-backend-events"

[[pubsub]]
binding = "CROSS_REGION"
namespace = "arbitragex-cross-region"

# ========================================
# Environment Variables
# ========================================
[vars]
ENVIRONMENT = "production"
CONTABO_BACKEND_URL = "https://your-contabo-ip:8081"
RATE_LIMIT_REQUESTS = "1000"
RATE_LIMIT_WINDOW = "900"
SECURITY_HEADERS_ENABLED = "true"
CORS_ORIGINS = "https://your-lovable-frontend.com"
JWT_EXPIRY = "3600"
CACHE_TTL_API = "300"
CACHE_TTL_STATIC = "3600"
CACHE_TTL_DATABASE = "180"

# ========================================
# Routes Configuration
# ========================================
[routes]
pattern = "arbitragex.pages.dev/api/proxy/*"
zone_name = "arbitragex.pages.dev"

[routes]
pattern = "arbitragex.pages.dev/security/*"
zone_name = "arbitragex.pages.dev"

[routes]
pattern = "arbitragex.pages.dev/analytics/*"
zone_name = "arbitragex.pages.dev"

[routes]
pattern = "arbitragex.pages.dev/ws/*"
zone_name = "arbitragex.pages.dev"

# ========================================
# Build Configuration
# ========================================
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "modules"
dir = "./dist"
main = "./index.js"

# ========================================
# Development Configuration
# ========================================
[env.development]
name = "arbitragex-edge-dev"

[env.development.vars]
ENVIRONMENT = "development"
CONTABO_BACKEND_URL = "http://localhost:8081"
CORS_ORIGINS = "*"

# ========================================
# Staging Configuration
# ========================================
[env.staging]
name = "arbitragex-edge-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
CONTABO_BACKEND_URL = "https://staging-contabo-ip:8081"

# ========================================
# Workers Configuration
# ========================================

# API Proxy Workers
[[workers]]
name = "arbitragex-api-proxy-opportunities"
script = "workers/api-proxy/opportunities.ts"
compatibility_date = "2024-09-08"

[[workers]]
name = "arbitragex-api-proxy-strategies"
script = "workers/api-proxy/strategies.ts"
compatibility_date = "2024-09-08"

[[workers]]
name = "arbitragex-api-proxy-executions"
script = "workers/api-proxy/executions.ts"
compatibility_date = "2024-09-08"

[[workers]]
name = "arbitragex-api-proxy-analytics"
script = "workers/api-proxy/analytics.ts"
compatibility_date = "2024-09-08"

# Security Workers
[[workers]]
name = "arbitragex-security-jwt"
script = "workers/security/jwt-validation.ts"
compatibility_date = "2024-09-08"

[[workers]]
name = "arbitragex-security-rate-limit"
script = "workers/security/rate-limiting.ts"
compatibility_date = "2024-09-08"

[[workers]]
name = "arbitragex-security-ddos"
script = "workers/security/ddos-protection.ts"
compatibility_date = "2024-09-08"

[[workers]]
name = "arbitragex-security-geo"
script = "workers/security/geo-control.ts"
compatibility_date = "2024-09-08"

# Optimization Workers
[[workers]]
name = "arbitragex-optimization-compression"
script = "workers/optimization/compression.ts"
compatibility_date = "2024-09-08"

[[workers]]
name = "arbitragex-optimization-caching"
script = "workers/optimization/caching.ts"
compatibility_date = "2024-09-08"

[[workers]]
name = "arbitragex-optimization-batching"
script = "workers/optimization/batching.ts"
compatibility_date = "2024-09-08"

# Analytics Workers
[[workers]]
name = "arbitragex-analytics-metrics"
script = "workers/analytics/metrics.ts"
compatibility_date = "2024-09-08"

[[workers]]
name = "arbitragex-analytics-performance"
script = "workers/analytics/performance.ts"
compatibility_date = "2024-09-08"

[[workers]]
name = "arbitragex-analytics-alerting"
script = "workers/analytics/alerting.ts"
compatibility_date = "2024-09-08"