# ArbitrageX Supreme V3.0 - Grafana Datasources Configuration
# Automated provisioning of data sources for monitoring dashboards

apiVersion: 1

# Delete existing datasources before inserting new ones
deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1

# Datasources configuration
datasources:
  # Primary Prometheus datasource for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    orgId: 1
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      cacheLevel: 'High'
      disableMetricsLookup: false
      incrementalQuerying: true
      incrementalQueryOverlapWindow: 10m
      queryTimeout: 60s
      timeInterval: 15s
    secureJsonData: {}
    uid: prometheus-uid

  # Loki datasource for log aggregation
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    orgId: 1
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: "TraceID"
          matcherRegex: "trace_id=(\\w+)"
          url: "http://jaeger:16686/trace/$${__value.raw}"
          datasourceUid: jaeger-uid
    uid: loki-uid

  # TestData datasource for development and testing
  - name: TestData
    type: testdata
    access: proxy
    orgId: 1
    version: 1
    editable: true
    jsonData: {}
    uid: testdata-uid

# Optional: Additional datasources for enhanced monitoring
  # InfluxDB for high-frequency time series (if needed)
  # - name: InfluxDB
  #   type: influxdb
  #   access: proxy
  #   url: http://influxdb:8086
  #   database: arbitragex
  #   user: arbitragex
  #   orgId: 1
  #   version: 1
  #   editable: true
  #   jsonData:
  #     timeInterval: "5s"
  #   secureJsonData:
  #     password: ${INFLUXDB_PASSWORD}
  #   uid: influxdb-uid

  # Jaeger for distributed tracing (if implemented)
  # - name: Jaeger
  #   type: jaeger
  #   access: proxy
  #   url: http://jaeger:16686
  #   orgId: 1
  #   version: 1
  #   editable: true
  #   jsonData:
  #     tracesToLogs:
  #       datasourceUid: loki-uid
  #       tags: ['job', 'instance', 'pod', 'namespace']
  #       mappedTags: [{ key: 'service.name', value: 'service' }]
  #       mapTagNamesEnabled: true
  #       spanStartTimeShift: '-1h'
  #       spanEndTimeShift: '1h'
  #   uid: jaeger-uid